package com.github.taxbeans.forms.nz;

import org.javamoney.moneta.Money;

public enum IR7PFields {
	partnershipName,
	irdNumber,
	partnersName1,
	partnersIRDNumber1,
	partnersInterest1,
	partnersDividends1,
	partnersMA1,
	partnersOA1,
	partnersRentalIncome1,
	partnersPassiveIncome1,
	partnersOtherIncome1,
	partnersLAQCLoss1,
	partnersTotalIncome1,
	partnersProportion1,
	partnersExtinguishedLosses1,
	partnersOverseasTaxPaid1,
	partnersImputationCredits1,
	partnersOtherTaxCredits1,
	partnersName2,
	partnersIRDNumber2,
	partnersInterest2,
	partnersDividends2,
	partnersMA2,
	partnersOA2,
	partnersRentalIncome2,
	partnersPassiveIncome2,
	partnersOtherIncome2,
	partnersLAQCLoss2,
	partnersTotalIncome2,
	partnersProportion2,
	partnersExtinguishedLosses2,
	partnersOverseasTaxPaid2,
	partnersImputationCredits2,
	partnersOtherTaxCredits2,
	partnersTotalResidentialIncome1,
	partnersTotalResidentialIncome2,
	residentialRentalDeductions1,
	residentialRentalDeductions2;
}
