// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.github.taxbeans.model.assertions;

import java.math.BigDecimal;
import java.time.LocalDate;

public class BalanceAssertionBuilder extends BalanceAssertionBuilderBase<BalanceAssertionBuilder> {
	public static BalanceAssertionBuilder balanceAssertion() {
		return new BalanceAssertionBuilder();
	}

	public BalanceAssertionBuilder() {
		super(new BalanceAssertion());
	}

	public BalanceAssertion build() {
		return getInstance();
	}
}

class BalanceAssertionBuilderBase<GeneratorT extends BalanceAssertionBuilderBase<GeneratorT>> {
	private BalanceAssertion instance;

	protected BalanceAssertionBuilderBase(BalanceAssertion aInstance) {
		instance = aInstance;
	}

	protected BalanceAssertion getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBalance(BigDecimal aValue) {
		instance.setBalance(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDate(LocalDate aValue) {
		instance.setDate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNumber(int aValue) {
		instance.setNumber(aValue);

		return (GeneratorT) this;
	}
}
